version: '3.9'

services:
  db:
    container_name: db
    image: postgres:14
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo@1988      
      - POSTGRES_DB=postgres
    restart: always             # * run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    networks:
      - networks-bridge
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_SERVER_MODE: "True"
      PGADMIN_SERVER_JSON_FILE: "/pgadmin4/servers.json"
    ports:
      - "5050:80"
    volumes:
      - ./etc/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    restart: always  
    networks:
      - networks-bridge
      
  odoo:
    container_name: odoo
    build:
      context: .
      dockerfile: odoo.dockerfile
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072" # * live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo@1988
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # * run as a service
    networks:
      - networks-bridge

networks:
  networks-bridge:
    driver: bridge